Auth functionality
OKEPL/multi-annotator pull request #16
Opened 2019-11-06 11:37 UTC by wiola-dreszler

2019-11-06 13:50 UTC, Tantael commented on docker-compose.dev.yml
> +      - 0.0.0.0:8080:8080
Pick only one port that you actually need

2019-11-06 14:01 UTC, Tantael requested changes
Please resolve comments in review

2019-11-06 14:01 UTC, Tantael commented on client/Dockerfile
> +EXPOSE 8080
Expose only port that you actually need

2019-11-06 14:01 UTC, Tantael commented on client/Dockerfile
> +CMD npm run start
add new line at end of file

2019-11-06 14:01 UTC, Tantael commented on client/src/Auth/Auth.tsx
> +                                <Link href="https://github.com/jsbroks/Multi-annotator/issues">
not existing link! change to https://github.com/OKEPL/multi-annotator/issues

2019-11-06 14:01 UTC, Tantael commented on docker-compose.dev.yml
> +      - 0.0.0.0:8080:8080
Pick only one port that you actually need

2019-11-06 14:44 UTC, maciejdrozdowski requested changes

2019-11-06 14:44 UTC, maciejdrozdowski commented on client/src/Auth/auth.api.ts
> +    error?: string;
According to this interface, response from api might include only one error field, without information about success data fields. The same issue concern RegisterResponse...
I suggest to define ApiErrorInterface and make union type with success response interface.

2019-11-06 14:44 UTC, maciejdrozdowski commented on client/src/Auth/auth.hooks.tsx
> +    fetchUsersInfo();
This method should be invoked inside useEffect hook ( if possible with "guard-param" or only once )

2019-11-06 14:44 UTC, maciejdrozdowski commented on client/src/Auth/TabPanel.tsx
> +    } = useTabPanel();
Hmmm... Perhaps it is a good idea to uplift this hook to Auth.tsx file and pass props like "loginMode","ButtonText" and "SubmitCb" instead passing "activeTab" and "index" and then decide internally which action should be performed ?

2019-11-07 14:43 UTC, wojciech-bilicki requested changes

2019-11-07 14:43 UTC, wojciech-bilicki commented on client/src/Auth/auth.api.ts
> +    const totalUsers = response.data.total_users;
or just unpack the response?

2019-11-07 14:43 UTC, wojciech-bilicki commented on client/src/Auth/auth.hooks.tsx
> +    };
new line missing

2019-11-07 14:43 UTC, wojciech-bilicki commented on client/src/Auth/tabPanel.hooks.tsx
> +    };
new line missing

2019-11-07 14:43 UTC, wojciech-bilicki commented on client/src/common/api.ts
> +    }
new line

2019-11-15 09:49 UTC, wojciech-bilicki submitted a review, later dismissed

2019-11-18 12:54 UTC, maciejdrozdowski approved these changes

2019-11-20 11:12 UTC, Tantael approved these changes

2019-11-20 11:20 UTC, merged