Add Admin Select fixes #8
OKEPL/multi-annotator pull request #24
Opened 2019-11-27 09:51 UTC by wiola-dreszler

2019-11-27 10:28 UTC, wojciech-bilicki requested changes

2019-11-27 10:28 UTC, wojciech-bilicki commented on client/src/App/Header/Header.tsx
> +                            onLogoutCb={onLogoutCb}
Don't use abbreviations like `Cb`. If you want to have full name please change it to `callback`, but in my opinion `onLogout` as a name is sufficient.

2019-11-27 10:28 UTC, wojciech-bilicki commented on client/src/App/Header/Header.tsx
> +                        onLogoutCb={onLogoutCb}
ditto

2019-11-27 10:28 UTC, wojciech-bilicki commented on client/src/App/Header/MenuDesktop.tsx
> +                <UserSelect currentUser={currentUser} onLogoutCb={onLogoutCb} />
So here's an interesting thought... you're passing `onLogoutCb` few levels deep into the component tree. How about storing this in a Context?

2019-11-27 10:28 UTC, wojciech-bilicki commented on client/src/App/Header/header.hooks.ts
>      let menuItems: Array<NavItem> = [];
why is this let and not a const?

2019-11-27 10:28 UTC, wojciech-bilicki commented on client/src/Auth/authenticatedRoute.tsx
> +        context.currentUser && context.currentUser.is_admin
why do we have `is_admin` and not `isAdmin`? Shouldn't everything be camelCased?

2019-11-28 11:44 UTC, maciejdrozdowski approved these changes

2019-11-28 12:23 UTC, wojciech-bilicki approved these changes

2019-11-28 12:24 UTC, merged