Add Datasets Page
OKEPL/multi-annotator pull request #25
Opened 2019-11-27 11:29 UTC by maciejdrozdowski

- Adjust GlobalContext state -> from now on it will return [state, dispatch] object
- Move GlobalContext actions definitions to globalActions file
- Add Body of Datasets Page
- Add Datasets related requests
- Add common > components folder (reusable components for all pages)
- Add material-ui-flat-pagination library to handle pagination
- Add Formik & Yup libaries to handle Form state

2019-11-27 11:42 UTC, wojciech-bilicki requested changes

2019-11-27 11:42 UTC, wojciech-bilicki commented on client/src/Datasets/datasets.api.tsx
> +    const url = `${baseURL}/data?page=${page}&limit=${limit}`;
we should send the URL query parameters using params dictionary in axis

2019-11-27 11:42 UTC, wojciech-bilicki commented on client/src/Datasets/datasets.api.tsx
> +    const url = `${baseURL}/?name=${name}`;
ditto

2019-11-27 11:42 UTC, wojciech-bilicki commented on client/src/Datasets/datasets.hooks.ts
> +    const [_globalState, dispatch] = useGlobalContext();
you should be able to replace the `_globalState` with just `_` and eslint is going to play nicely

2019-11-27 11:42 UTC, wojciech-bilicki commented on client/src/common/components/Formik/TextField.tsx
> +    formik: FormikProps<any>;
We are we using `any` type here?

2019-11-28 11:37 UTC, wojciech-bilicki approved these changes

2019-11-28 11:41 UTC, wiola-dreszler approved these changes

2019-11-28 11:41 UTC, merged