Added Auth view fixes #2
OKEPL/multi-annotator pull request #3
Opened 2019-10-24 11:30 UTC by wiola-dreszler

2019-10-24 13:09 UTC, maciejdrozdowski commented on client/src/Auth/TabPanel.tsx
> +import { Button } from "@material-ui/core";
Please replace with import Button from"@material-ui/core/Button"

2019-10-24 13:16 UTC, maciejdrozdowski requested changes
Replace button import

2019-10-24 13:29 UTC, wojciech-bilicki requested changes

2019-10-24 13:29 UTC, wojciech-bilicki commented on client/src/App.tsx
>      <div>
why do we need divs here? Aren't those obsolete?

2019-10-24 13:29 UTC, wojciech-bilicki commented on client/src/Auth/Auth.components.tsx
> +    color: "#000",
all colours should be defined in theme, so that we can change them easily later if needed

2019-10-24 13:29 UTC, wojciech-bilicki commented on client/src/Auth/Auth.tsx
> +import Container from "@material-ui/core/Container";
You could import all those components in one line by importing from `@material-ui/core`

2019-10-24 13:29 UTC, wojciech-bilicki commented on client/src/Auth/Auth.tsx
> +              {"If you have any questions please checkout the "}
Do we need curly braces here?

2019-10-24 13:29 UTC, wojciech-bilicki commented on client/src/Auth/Auth.tsx
> +            TabIndicatorProps={{style: {background: 'transparent'}}}
Do we need inline styles here?

2019-10-24 13:29 UTC, wojciech-bilicki commented on client/src/Auth/TabPanel.tsx
> +  const [credentials, setCredentials] = useState({
you can unpack credentials here. It will save you creating intermediating variables in lines 25 to 28

2019-10-24 13:29 UTC, wojciech-bilicki commented on client/src/Auth/TabPanel.tsx
> +    if (!username || isValidUsername) {
Please check the logic of the validation, because it seems flipped.

2019-10-24 13:29 UTC, wojciech-bilicki commented on client/src/Auth/TabPanel.tsx
> +    if (!username || isValidUsername) {
ditto

2019-10-24 13:29 UTC, wojciech-bilicki commented on client/src/Auth/TabPanel.tsx
> +      setError("");
Can we actually replace the error with `null`?

2019-10-24 13:29 UTC, wojciech-bilicki commented on client/src/Auth/TabPanel.tsx
> +  };
```
const handleChange = ({target: {name, value}}) => {
   setCredentials({...credentials, [name]: value]
}
```

No need to create a function returning a function when you can store the field name in JSX

2019-10-24 13:29 UTC, wojciech-bilicki commented on client/src/Auth/TabPanel.tsx
> +        onSubmit={index === 1 ? register : login}
Instead of this magic number 1 can we define a constant for it like
const LOGIN_TAB_INDEX = 1;

2019-10-24 13:29 UTC, wojciech-bilicki commented on client/src/Auth/TabPanel.tsx
> +  const isValidPassword = !!password && password.length < 5;
no magic numbers plz
`const PASSWORD_LENGTH_LIMIT = 5`

2019-10-25 12:51 UTC, maciejdrozdowski approved these changes

2019-10-28 08:50 UTC, wojciech-bilicki approved these changes

2019-10-28 08:51 UTC, merged