Add dataset page layout
OKEPL/multi-annotator pull request #35
Opened 2019-12-04 14:13 UTC by maciejdrozdowski

- Add Dataset details Layout ( without api calls )
- Rename Datasets into Dataset > List

2019-12-05 09:58 UTC, wojciech-bilicki requested changes

2019-12-05 09:58 UTC, wojciech-bilicki commented on client/src/Dataset/Details/Images/Images.tsx
> +                    onClick={(e, offset) => setPage(offset)}
if you're not using argument given by function it's a common practice to replace it with `_` in TypeScript.

`(_, offset)`

2019-12-05 09:58 UTC, wojciech-bilicki commented on client/src/Dataset/Details/Panel/FilterForm.tsx
> +                        <MenuItem value={'File Name'}>File Name</MenuItem>
you don't need to wrap strings is curly braces when you're passing them as props

2019-12-05 09:58 UTC, wojciech-bilicki commented on client/src/Dataset/Details/Panel/SubdirForm.tsx
> +                onChange={(e: ChangeEvent<{ value: unknown }>) => {
why is the value here `unknown`?

2019-12-05 09:58 UTC, wojciech-bilicki commented on client/src/Dataset/Details/Statistics/Statistics.tsx
> +    if (stats == null) {
please use strict comparison everywhere

2019-12-05 09:58 UTC, wojciech-bilicki commented on client/src/Dataset/Details/Tabs.tsx
> +            onChange={(event: ChangeEvent<{}>, newValue: number) => {
use `_` to ignore the event argument

2019-12-05 09:58 UTC, wojciech-bilicki commented on client/src/Dataset/Details/details.hooks.tsx
> +        openAnnotator: openAnnotator,
ES6 please :)

2019-12-05 09:58 UTC, wojciech-bilicki commented on client/src/Dataset/Details/details.hooks.tsx
> +    const openAnnotator = (id: number) => {
this function is static against its arguments you don't have to recreate it every time you call `usePageNavigation`. Move it to outer scope.

2019-12-05 09:58 UTC, wojciech-bilicki commented on client/src/Dataset/datasets.api.tsx
> +        page: page,
srsly...`es6`

2019-12-05 09:58 UTC, wojciech-bilicki commented on client/src/Dataset/datasets.api.tsx
> +    const response = await Api.get(url, { params: params });
dude...`es6`...ever heard of it?

2019-12-05 09:58 UTC, wojciech-bilicki commented on client/src/Dataset/datasets.api.tsx
> +        name: name,
https://media.giphy.com/media/tEG1nF1v7AL8A/giphy.gif

2019-12-05 09:58 UTC, wojciech-bilicki commented on client/src/Dataset/datasets.api.tsx
> +        folder: folder,
ditto

2019-12-05 09:58 UTC, wojciech-bilicki commented on client/src/Dataset/datasets.api.tsx
> +    id: number,
functions that take more than one arg should take object as a param to avoid problems with argument ordering

2019-12-05 09:58 UTC, wojciech-bilicki commented on client/src/Dataset/datasets.api.tsx
> +    const response = await Api.get<{
extract this type so some interface please

2019-12-06 10:16 UTC, wojciech-bilicki approved these changes

2019-12-06 10:31 UTC, wiola-dreszler approved these changes

2019-12-06 10:32 UTC, merged