Refactoring and cleaning
OKEPL/multi-annotator pull request #36
Opened 2019-12-05 10:09 UTC by Kecz

2019-12-06 09:51 UTC, Dumbldore commented on backend/tests/api/test_category.py
>          pass
Write tests

2019-12-06 10:01 UTC, Dumbldore commented on backend/tests/api/test_dataset.py
> +            return matched_elem["id"]
What's the point here?

2019-12-06 10:11 UTC, Dumbldore commented on backend/workers/lib/vod_converter/detrac.py
> +                for frame in toor.iter("frame"):  # child = frame
what is this comment?

2019-12-06 10:12 UTC, Dumbldore reviewed
some small fixes needed

2019-12-09 09:00 UTC, korjak requested changes
Few fixes required, the most crucial is re-adding the credentials file

2019-12-09 09:00 UTC, korjak commented on backend/workers/lib/vod_converter/split_labels_from_json_string.py
>      return splitted_labels
is that file even used in annotator?

2019-12-09 09:00 UTC, korjak commented on backend/workers/lib/vod_converter/udacity.py
> -class UdacityCrowdAIIngestor(Ingestor):
why delete this file?

2019-12-09 09:00 UTC, korjak commented on backend/workers/tasks/data.py
> +                      f"({annotation_counter+1}/{total_annotations})")
is that correct syntax?

2019-12-09 09:00 UTC, korjak commented on backend/workers/tasks/data.py
> +                      f"({annotation_counter+1}/{total_annotations})")
questioning syntax again

2019-12-09 09:00 UTC, korjak commented on backend/tests/cred.json
> -{"username": "korjak", "password": "korjak"}
credentials are required to complete all tests, thus this file cannot be deleted

2019-12-09 09:03 UTC, korjak commented on backend/tests/api/test_dataset.py
> +            return matched_elem["id"]
> What's the point here?

what do you mean?

2019-12-09 09:13 UTC, Kecz commented on backend/workers/lib/vod_converter/split_labels_from_json_string.py
>      return splitted_labels
yes, it is used  to split to huge coco jsons

2019-12-09 09:14 UTC, Kecz commented on backend/workers/lib/vod_converter/udacity.py
> -class UdacityCrowdAIIngestor(Ingestor):
It is not used now, it may be restored if needed

2019-12-09 09:16 UTC, Kecz commented on backend/tests/cred.json
> -{"username": "korjak", "password": "korjak"}
Ok, reverting this file with default data

2019-12-09 10:02 UTC, Dumbldore approved these changes

2019-12-09 10:41 UTC, korjak approved these changes

2019-12-09 10:51 UTC, merged