Add Admin Panel Page fixes #9
OKEPL/multi-annotator pull request #38
Opened 2019-12-10 10:14 UTC by wiola-dreszler

- Add Admin Panel Page

- Update TextField.tsx file

- Fix List form

2019-12-10 11:51 UTC, wojciech-bilicki requested changes

2019-12-10 11:51 UTC, wojciech-bilicki commented on client/src/AdminPanel/AdminPanel.tsx
> +                        <MenuItem value={50}>50</MenuItem>
This are quantified values so I believe they should be stored in some kind of `enum` with descriptive name

2019-12-10 11:51 UTC, wojciech-bilicki commented on client/src/AdminPanel/AdminTable.tsx
> +                            <TableCell
I believe that this `TableCell` should be extracted to separate file as separate component

2019-12-12 08:34 UTC, wojciech-bilicki approved these changes

2019-12-12 08:48 UTC, maciejdrozdowski approved these changes

2019-12-12 08:49 UTC, merged