Add Admin User Settings Page fixes #10
OKEPL/multi-annotator pull request #39
Opened 2019-12-12 10:54 UTC by wiola-dreszler

2019-12-12 12:41 UTC, wojciech-bilicki requested changes

2019-12-12 12:41 UTC, wojciech-bilicki commented on client/package.json
> +    "notistack": "^0.9.7",
do we need separate snackbar library? Material UI should have this component included.

2019-12-12 12:41 UTC, wojciech-bilicki commented on client/src/UserSettings/userSettings.hooks.ts
> +    const displayName = name ? name : username;
`name || username`

2019-12-13 09:08 UTC, wojciech-bilicki approved these changes

2019-12-13 09:26 UTC, maciejdrozdowski approved these changes

2019-12-13 09:27 UTC, merged