Add Tasks Page fixes #30
OKEPL/multi-annotator pull request #49
Opened 2020-01-13 09:56 UTC by wiola-dreszler

2020-01-14 08:28 UTC, maciejdrozdowski requested changes

2020-01-14 08:28 UTC, maciejdrozdowski commented on client/src/Tasks/tasks.hooks.ts
> +        if (!scheduler.length) {
empty condition

2020-01-14 08:28 UTC, maciejdrozdowski commented on client/src/Tasks/TaskRow.tsx
> +                                    color={dictionary[l.type]}
No need for extra type in case of single use-case.
Also 'dictionary' name is little vague

2020-01-14 09:30 UTC, wojciech-bilicki requested changes

2020-01-14 09:30 UTC, wojciech-bilicki commented on client/src/Tasks/TaskRow.tsx
> +const TaskRow: React.FC<Props> = ({ task, routeId, deleteTask }) => {
you can unpack `task` here so you won't repeat yourself below when using `task.` in few places

2020-01-14 09:30 UTC, wojciech-bilicki commented on client/src/Tasks/TaskRow.tsx
> +                            {filteredLogs.map((l: Logs) => (
the type name should be in singular `Log` instead of plural `Logs`. Plural name always references the array of something

2020-01-14 09:30 UTC, wojciech-bilicki commented on client/src/Tasks/taskRow.hooks.ts
> +    const showLogs = task.id === routeId;
boolean values should have names starting with `is`, `are`, `should` etc.

2020-01-14 09:30 UTC, wojciech-bilicki commented on client/src/Tasks/taskRow.hooks.ts
> +    const [logs, setLogs] = useState<Logs[]>([]);
type name should be singular

2020-01-14 09:30 UTC, wojciech-bilicki commented on client/src/Tasks/taskRow.hooks.ts
> +    const completed = task.completed || task.progress >= TASK_COMPLETED;
`TASK_COMPLETED` is being compared to some numerical value here therefore we should change it name to something like `TASK_COMPLETED_TRESHOLD_VALUE`

2020-01-14 09:30 UTC, wojciech-bilicki commented on client/src/Tasks/taskRow.hooks.ts
> +    const scrollToBottom = () => {
this function is being recreated every time we call useTaskRow. Move it to module scope and make it take taskRef as an argument, so we won't recreate it.

2020-01-14 09:30 UTC, wojciech-bilicki commented on client/src/Tasks/tasks.hooks.ts
> +    const taskKeys = Array.from(new Set(list.tasks.map(item => item.group)));
are we using `Set` here for unique values?

2020-01-14 09:30 UTC, wojciech-bilicki commented on client/src/Tasks/tasks.hooks.ts
> +    const [scheduler, setScheduler] = useState<any>([]);
no `any` types

2020-01-14 09:30 UTC, wojciech-bilicki commented on client/src/Tasks/tasks.hooks.ts
> +            );
I don't get it. You initialise the array to just overwrite it in the next line. Why not use map on `tasks` instead and make newArr a const? Also `newArr` name doesn't hold any information to it. Change it to something more informative.

2020-01-17 07:25 UTC, wojciech-bilicki approved these changes

2020-01-17 09:02 UTC, maciejdrozdowski approved these changes

2020-01-17 09:03 UTC, merged