Annotator add basic Tools & Panels
OKEPL/multi-annotator pull request #50
Opened 2020-01-17 13:58 UTC by maciejdrozdowski

0) Create dedicated annotator.types file for all internal types used in annotator

1) Basic Hooks changes
- remove annotator.hooks.tsx and move its content to dedicated simpler hooks
- Create Info Folder for all hooks related with user decisions, selected things, filters (etc etc) - all related with react state
- Create useChoices, useFetch, useInfo, useCursor, useFilter into Info folder

2) Paper Hooks changes
- remove painter hook from annotator.hooks.tsx
- move useCanvas hook into Paper folder
- Create Paper folder for ALL hooks & methods & components which use paper.js scope objects ( mainly references )
- Create Paper/Tools subfolder for all hooks related with Paper.Tool ( object which handle mouse & keyboard in various useCases )
- add 'useTools' hook which gather/manage all Tools states
- Add 'BBox' and 'Eraser' Tools for Paper/tools ( create rectangle shape + rubber )
- Create Paper/Utils subfolder for all reusable paper.js methods
- Create Paper/Part subfolder for all components which use paper.js objects
- Create Paper/Various subfolder for every other paper.js hooks

3) Add Right Panel CategoryCard & AnnotationCard - it handle enabled actions correctly

4) Add Category filter field

5) Adjust BBox & Eraser Tools Panels

2020-01-20 14:28 UTC, wojciech-bilicki requested changes

2020-01-20 14:28 UTC, wojciech-bilicki commented on client/src/Annotator/Annotator.tsx
> +import { Part } from './Paper';
you import twice from the same module. Check line 11

2020-01-20 14:28 UTC, wojciech-bilicki commented on client/src/Annotator/Annotator.tsx
> +                            info.data.map(g => (
`g` isn't very informative variable name

2020-01-20 14:28 UTC, wojciech-bilicki commented on client/src/Annotator/Info/useChoices.tsx
> +            annotation: annotationId ? annotationId : null,
it's annotationId, not the whole annotation object. The name of the entry in state is misleading.

2020-01-20 14:28 UTC, wojciech-bilicki commented on client/src/Annotator/Info/useCursor.tsx
> +                cursor = 'pointer';
values that are assigned to cursor should also be grouped in an enum since they are a closed set.

2020-01-20 14:28 UTC, wojciech-bilicki commented on client/src/Annotator/Info/useFetch.tsx
> +const useFetch = (imageId: number) => {
useFetch isn't a proper name for this hook. It is named like a hook that would use standard `fetch` functionality from a browser to perform XHR request.

2020-01-20 14:28 UTC, wojciech-bilicki commented on client/src/Annotator/Info/useFilter.tsx
> +        const cats = categories.filter(category =>
![](http://becomeawag.com/wp-content/uploads/2019/09/coughing-cat-know-your-meme-6.png)

Please change the variable name

2020-01-20 14:28 UTC, wojciech-bilicki commented on client/src/Annotator/Info/useInfo.tsx
> +    setCategoryEnabled: (catId: number) => void;
`categoryId`

2020-01-20 14:28 UTC, wojciech-bilicki commented on client/src/Annotator/Paper/Part/AnnotationInfo.tsx
> +
Maybe do an early return instead of nested ifs?

2020-01-20 14:28 UTC, wojciech-bilicki commented on client/src/Annotator/Paper/Part/AnnotationInfo.tsx
> +        if (group != null) {
ditto

2020-01-20 14:28 UTC, wojciech-bilicki commented on client/src/Annotator/Paper/Part/AnnotationInfo.tsx
> +        if (group != null) {
ditto

2020-01-20 14:28 UTC, wojciech-bilicki commented on client/src/Annotator/Paper/Part/AnnotationInfo.tsx
> +    return null;
all those functions seem a bit the same. Anything we can do to factor out a common function to make it DRY?

2020-01-20 14:28 UTC, wojciech-bilicki commented on client/src/Annotator/Paper/Tool/useEraser.tsx
> +    const [radius, _setRadius] = useState(30);
magic repeated number

2020-01-20 14:28 UTC, wojciech-bilicki commented on client/src/Annotator/Paper/Utils/pathUtils.tsx
> +    a.segmentation.forEach(polygon => {
one letter variable name aren't good. I assume that your IDE has autocompletion so a longer name not gonna hurt.

2020-01-20 14:28 UTC, wojciech-bilicki commented on client/src/Annotator/annotator.types.tsx
> +export type Maybe<T> = T | null;
`| undefined` is a proper definition of `Maybe` type for javascript

2020-01-21 09:23 UTC, wojciech-bilicki requested changes

2020-01-21 09:23 UTC, wojciech-bilicki commented on client/src/Annotator/Info/useChoices.tsx
> +            annotationId: annotationId ? annotationId : null,
this can be changed to `annotationId || null`

2020-01-21 09:23 UTC, wojciech-bilicki commented on client/src/Annotator/Info/useFilter.tsx
> +        _setSearchText(value ? value : '');
`value || ''`

2020-01-21 09:44 UTC, wojciech-bilicki approved these changes

2020-01-21 10:14 UTC, wiola-dreszler approved these changes

2020-01-21 10:14 UTC, merged