Dataset Details update
OKEPL/multi-annotator pull request #61
Opened 2020-02-28 11:42 UTC by wiola-dreszler

2020-02-28 12:54 UTC, maciejdrozdowski requested changes

2020-02-28 12:54 UTC, maciejdrozdowski commented on client/src/Dataset/Details/Details.tsx
> +                                handleMouseDown(event);
onMouseDown={handleMouseDown}

2020-03-02 08:24 UTC, wojciech-bilicki requested changes

2020-03-02 08:24 UTC, wojciech-bilicki commented on client/src/Dataset/Details/Details.tsx
> +                            onMouseDown={(event: React.MouseEvent) => {
if you pass the default argument to the handler function then there's no need to create new function
```suggestion
                            onMouseDown={handleMouseDown}
```

2020-03-02 08:24 UTC, wojciech-bilicki commented on client/src/Dataset/Details/Images/Images.tsx
> +                                            downloadImageAction(
function that takes two or more args should accept the object to use named params

2020-03-02 08:24 UTC, wojciech-bilicki commented on client/src/Dataset/datasets.api.tsx
> +export const generate = async (id: number, keyword: string, limit: string) => {
function taking few args should accept object as an argument

2020-03-02 09:28 UTC, wojciech-bilicki approved these changes

2020-03-02 10:44 UTC, maciejdrozdowski approved these changes

2020-03-02 10:44 UTC, merged